CREATE TABLE dbo.[WorkDetail]
(
    ID INT IDENTITY(1,1) NOT NULL,
    UserId INT NOT NULL,
    StartDate datetime NOT NULL,
    EndDate datetime NOT NULL,
    Title NVARCHAR(100) NOT NULL,
    Location NVARCHAR(100) NOT NULL,
    Company NVARCHAR(100) NOT NULL,
    Detail NVARCHAR(MAX) NOT NULL,
    CONSTRAINT [PK_WorkDetail_ID] PRIMARY KEY CLUSTERED (ID ASC),
    CONSTRAINT FK_WorkDetail_UserID FOREIGN KEY (UserId) REFERENCES dbo.[User] (ID) ON DELETE CASCADE ON UPDATE CASCADE  
);


CREATE TABLE dbo.[ProjectDetail]
(
    ID INT IDENTITY(1,1) NOT NULL,
    UserId INT NOT NULL,
    StartDate datetime NOT NULL,
    EndDate datetime NOT NULL,
    Title NVARCHAR(100) NOT NULL,
    Supervisor NVARCHAR(100) NOT NULL,
    Company NVARCHAR(100) NOT NULL,
    Detail NVARCHAR(MAX) NOT NULL,
    CONSTRAINT [PK_ProjectDetail_ID] PRIMARY KEY CLUSTERED (ID ASC),
    CONSTRAINT FK_ProjectDetail_UserID FOREIGN KEY (UserId) REFERENCES dbo.[User] (ID) ON DELETE CASCADE ON UPDATE CASCADE  
);

CREATE TABLE dbo.[EducationSkill]
(
    ID INT IDENTITY(1,1) NOT NULL,
    UserId INT NOT NULL,
    StartDate datetime NOT NULL,
    EndDate datetime NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Degree NVARCHAR(100) NOT NULL,
    Achievements NVARCHAR(MAX) NOT NULL,
    CONSTRAINT [PK_EducationSkill_ID] PRIMARY KEY CLUSTERED (ID ASC),
    CONSTRAINT FK_EducationSkill_UserID FOREIGN KEY (UserId) REFERENCES dbo.[User] (ID) ON DELETE CASCADE ON UPDATE CASCADE  
);

CREATE TABLE dbo.[CertDetail]
(
    ID INT IDENTITY(1,1) NOT NULL,
    UserId INT NOT NULL,
    DateAchieved datetime NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Issuer NVARCHAR(100) NOT NULL,
    CONSTRAINT [PK_CertDetail_ID] PRIMARY KEY CLUSTERED (ID ASC),
    CONSTRAINT FK_CertDetail_UserID FOREIGN KEY (UserId) REFERENCES dbo.[User] (ID) ON DELETE CASCADE ON UPDATE CASCADE  
);

CREATE TABLE dbo.[SkillDetail]
(
    ID INT IDENTITY(1,1) NOT NULL,
    UserId INT NOT NULL,
    Level NVARCHAR(100) NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Class NVARCHAR(100) NOT NULL,
    CONSTRAINT [PK_SkillDetail_ID] PRIMARY KEY CLUSTERED (ID ASC),
    CONSTRAINT FK_SkillDetail_UserID FOREIGN KEY (UserId) REFERENCES dbo.[User] (ID) ON DELETE CASCADE ON UPDATE CASCADE  
);